### ISSUE TITLE
different 1-way anova result of type 3 vs type 1/2

### ISSUE THREAD

**Issue by babaq** [marcpabst/ANOVA.jl#19]
I have a dataset with just 1 factor, following the example on ReadMe, I got this result with the default type 3 anova:

![type3](https://user-images.githubusercontent.com/92771/69196811-6b76f200-0ae4-11ea-9918-9a5c5e7ee913.PNG)

but with type 2, it show this, which is what I expected.

![type2](https://user-images.githubusercontent.com/92771/69196817-703ba600-0ae4-11ea-859e-ce618ad0d7aa.PNG)

**Comment by marcpabst** [comment]
Hi there!

First of all, please note that I didn't really work on this for quite some time. I imagine, that there are more advanced ANOVA packages out there by now.

That said, for one factor, type I and II shouldn't  differ, as they are mathematically equivalent. You most certainly hit a bug here. My general advice is to go with type II - or even better balance your data (if possible), so that is doesn't matter which type you use. 

And as final word of caution: While often used in psychology and social sciences, statistician are not very fond of the idea of 'types' in ANOVA. (for all that matters, some even think that ANOVAs are a bad idea in the first place). 

Cheers,
Marc

**Comment by babaq** [comment]
Hi Marc,

Thanks for the explanations, my data are all balanced, so the type3 anova may have bug in the code.

I would prefer just GLM but people always talking about anova, so I have to do it. getting a anova from linear models would be helpful for those needing it.

Anyway, I hope someone would pick up what you already did.

Best,

Alex
